### ISSUE TITLE
CSS Fixes for the bookmarklet

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#1822]
I made a couple of fixes to the bookmarklet's CSS so it will show all apps even if the list extends beyond the window height and to make it more robust against interference by web pages, but I can't find the bookmarklet's CSS in the repository.

Anyway, here are my additions:
```css
  #wappalyzer-container {
    max-height: calc(100vh - 40px) !important;
  }

  #wappalyzer-apps {
    overflow-y: auto !important;
    max-height: calc(100vh - 73px) !important;
  }

  .wappalyzer-application img {
    width: 16px !important;
    height: 16px !important;
    display: inline-block !important;
  }
```

This should also resolve #1558. (The advantage over the fix in #1558 is that this one will keep the Close button visible at all times.)
